
export const FETCH_TIME_TABLE = 'FETCH_TIME_TABLE'

export const SET_VIDEO = 'SET_VIDEO'
export const CAL_PROCRESSING = 'CAL_PROCRESSING'
export const CURRENT_TIME_VIDEO = 'CURRENT_TIME_VIDEO'

export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET'